repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
