repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3.10
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
-    repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v1.2.3
     hooks:
     - id: trailing-whitespace
     - id: end-of-file-fixer
     - id: check-yaml
     - id: debug-statements
